<?php use Okami\Core\App; ?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $this->title ?></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
</head>
<body>

<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
            <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="/">
                Home
            </a>

            <a class="navbar-item" href="/contact">
                Contact
            </a>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <?php if (App::isGuest()) : ?>
                    <div class="buttons">
                        <a class="button is-primary" href="/register">
                            <strong>Sign up</strong>
                        </a>
                        <a class="button is-light" href="/login">
                            Log in
                        </a>
                    </div>
                <?php else: ?>
                    <a class="navbar-item" href="/profile">
                        Profile
                    </a>

                    <a class="button is-danger" href="/logout">
                        Logout
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</nav>
<section class="section">
    <div class="container">
        <?php if (App::$app->session->getFlash('success')) : ?>
            <div class="notification is-primary">
                <?php echo App::$app->session->getFlash('success') ?>
            </div>
        <?php endif; ?>
        {{content}}
    </div>
</section>
</body>
</html>