<?php

/** @var $model \App\Models\ContactForm */
/** @var $this \Okami\Core\View */

use Okami\Core\Form\Form;
use Okami\Core\Form\TextareaField;

$this->title = 'Profile';

?>

<h1 class="title">Contact us</h1>

<?php $form = Form::begin('', 'post'); ?>
    <?= $form->field($model, 'subject') ?>
    <?= $form->field($model, 'email') ?>
    <?= new TextareaField($model, 'body') ?>
    <div class="control">
        <button class="button is-link">Submit</button>
    </div>
<?= Form::end() ?>