<?php

    /** @var $model \App\Models\ContactForm */
    /** @var $this \Okami\Core\View */
    $this->title = 'Profile';

?>

<h1>Contact us</h1>

<?php $form = \Okami\Core\Form\Form::begin('', 'post'); ?>
<?= $form->field($model, 'subject') ?>
<?= $form->field($model, 'email') ?>
<?= $form->field($model, 'body') ?>
<button type="submit" class="btn btn-primary">Submit</button>
<?= \Okami\Core\Form\Form::end() ?>