<?php

/** @var $model \App\Models\ContactForm */
/** @var $this \Okami\Core\View */

use Okami\Core\Form\Form;
use Okami\Core\Form\TextareaField;

$this->title = 'Profile';

?>

<h1>Contact us</h1>

<?php $form = Form::begin('', 'post'); ?>
<?= $form->field($model, 'subject') ?>
<?= $form->field($model, 'email') ?>
<?= new TextareaField($model, 'body') ?>
<button type="submit" class="btn btn-primary">Submit</button>
<?= Form::end() ?>