<?php
/** @var $model \App\Models\User */
?>

<h1 class="title">Login</h1>

<?php $form = \Okami\Core\Form\Form::begin('', 'post') ?>
    <?php echo $form->field($model, 'email')->emailField() ?>
    <?php echo $form->field($model, 'password')->passwordField() ?>
    <div class="control">
        <button class="button is-link">Submit</button>
    </div>
<?php \Okami\Core\Form\Form::end('', 'post') ?>